/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/modules/**/*.{js,ts,jsx,tsx}',
    './src/shared/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#23272F',
        'primary-dark': '#F6F7F9',
        secondary: '#404756',
        'secondary-dark': '#EBECF0',
        tertiary: '#5E687E',
        'tertiary-dark': '#99A1B3',
        link: '#087EA4',
        'link-dark': '#58C4DC',
        highlight: '#E6F7FF',
        'highlight-dark': 'rgba(88,175,223,.1)',
        wash: '#FFFFFF',
        'wash-dark': '#23272F',
        card: '#F6F7F9',
        'card-dark': '#343A46',
        border: '#EBECF0',
        'border-dark': '#343A46',
        // Gray
        'gray-3': '#F9FAFB',
        'gray-5': '#F6F7F9',
        'gray-10': '#EBECF0',
        'gray-15': '#D0D3DC',
        'gray-20': '#BCC1CD',
        'gray-30': '#99A1B3',
        'gray-40': '#78839B',
        'gray-50': '#5E687E',
        'gray-60': '#4E5769',
        'gray-70': '#404756',
        'gray-80': '#343A46',
        'gray-90': '#23272F',
        'gray-95': '#16181D',
        // Blue
        'blue-5': '#E6F6FA',
        'blue-10': '#E6F7FF',
        'blue-20': '#ABE2ED',
        'blue-30': '#58C4DC',
        'blue-40': '#149ECA',
        'blue-50': '#087EA4',
        'blue-60': '#045975',
        'blue-80': '#043849',
        // Yellow
        'yellow-5': '#FEF5E7',
        'yellow-10': '#FDE7C7',
        'yellow-30': '#FABD62',
        'yellow-40': '#DB7D27',
        'yellow-50': '#C76A15',
        'yellow-60': '#B65700',
        // Purple
        'purple-5': '#F3F4FD',
        'purple-10': '#E7E9FB',
        'purple-20': '#C3C8F5',
        'purple-30': '#8891EC',
        'purple-40': '#6B75DB',
        'purple-50': '#575FB7',
        'purple-60': '#2B3491',
        // Green
        'green-5': '#F4FBF9',
        'green-10': '#E5F5F2',
        'green-20': '#ABDED5',
        'green-30': '#7FCCBF',
        'green-40': '#44AC99',
        'green-50': '#388F7F',
        'green-60': '#2B6E62',
        // Red
        'red-5': '#FAF1F0',
        'red-10': '#F2DBD9',
        'red-20': '#E5B7B3',
        'red-30': '#D07D77',
        'red-40': '#C1554D',
        'red-50': '#A6423A',
        'red-60': '#712D28',
      },
      boxShadow: {
        'inner-border': 'inset 0 0 0 1px rgba(0, 0, 0, 0.08)',
        'inner-border-dark': 'inset 0 0 0 1px rgba(255, 255, 255, 0.08)',
      },
      fontFamily: {
        text: [
          'Optimistic Text',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Helvetica',
          'Arial',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
        ],
        display: [
          'Optimistic Display',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Helvetica',
          'Arial',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
        ],
        mono: [
          'Source Code Pro',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      fontSize: {
        xs: '11px',
        sm: '13px',
        base: '15px',
        lg: '17px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '28px',
        '4xl': '32px',
        '5xl': '40px',
        '6xl': '52px',
      },
      lineHeight: {
        base: '30px',
        large: '38px',
        xl: '1.15',
      },
      screens: {
        xs: '374px',
        '3xl': '1919px',
      },
      gridTemplateColumns: {
        'only-content': 'auto',
        'sidebar-content': '20rem auto',
        'sidebar-content-toc': '20rem auto 20rem',
      },
      maxWidth: {
        '8xl': '96rem',
        'custom-xs': '21rem',
      },
    },
  },
  plugins: [],
};
